---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: startechnica-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://startechnica.github.io/apps
  timeout: 2m
